  name: check_develop_before_merge_on_main
  on:
    pull_request:
      types:
        - opened
      branches:
        - main
  jobs:
    run-this-test-when-merge_on_main:
      runs-on:
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Setup Java
          uses: actions/setup-java@v3
          with:
            java-version: 17
            distribution: 'adopt'

        - name: Set up Maven
          uses: stCarolas/setup-maven@v4.5
          with:
            maven-version: 3.8.2

        - name: Run regression
          run: mvn clean test -Dsurefire.suiteXmlFiles=regresion.xml

        - name: This is just test
          run: echo "This is a test for merging in to main"
