name: Regression test
on:
  [push,workflow_dispatch]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

  run-all-tests:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2

      - name: Run regression
        run: mvn clean test -Dsurefire.suiteXmlFiles=regresion.xml